### ISSUE TITLE
NFTs no longer showing, using cloud, did not touch app in about a month

### ISSUE THREAD

**Issue by Bobby-RobertQ** [MoralisWeb3/unity-web3-game-kit#120]
Our users can no longer see their nft's in the app. We have not updated the app in over a month, and we get this error from our users.

XoneOfficial2
v0.0.383

Android and iPhone

Get all logs in your terminal: [Learn about Moralis CLI](https://docs.moralis.io/moralis-server/tools/moralis-admin-cli#get-logs)
2022-08-08T20:45:31.580Z - Error: chain should not be empty, chain must be a valid enum value, 
    at fetch (/moralis-server/lib/cloud-code/plugins/helpers/apiUtils.js:218:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.Moralis.Web3API.<computed>.<computed> [as getNFTsForContract] (/moralis-server/lib/cloud-code/plugins/convenience/web3Api.js:31:81)
    at async eval (eval at customUserPlugin (/moralis-server/cloud/main.js:157:21), <anonymous>:1:576)
2022-08-08T20:45:31.577Z - Failed running cloud function getNFTsForContract for user qlv9xj9I8Zh2mHTICHgfRaRw with:
  Input: {"arr1":{"address":"0x573e5840d103d79b0285f16af64e23bc78278e54","token_address":"0x9Ec46a3dd227Fd5977C7F1997C043122a703FF2A","chainList":"eth"}}
  Error: {"message":"chain should not be empty, chain must be a valid enum value, ","code":141}
2022-08-08T20:23:58.119Z - Error: Invalid function: "pluginsReady"
    at handleCloudFunction (/moralis-server/lib/Routers/FunctionsRouter.js:201:13)
    at /moralis-server/lib/PromiseRouter.js:85:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Bobby-RobertQ** [comment]
One of our developers noted this was the solution "Needed to change the name of the argument passed from "chainList" to "chain"."
